### ISSUE TITLE
A way to hold things to one entry per process?

### ISSUE THREAD

**Issue by rpodric** [caoyue/WindowResizer#50] opened 2023-04-02 17:33 UTC
Can the program be configured to allow only one entry per process, or would that undermine some other functionality?

Inevitably I see multiples stacking up for things like Windows Explorer, a video player, browsers, etc.. This happens when I use Ctrl-Alt-S again for a new/better position. I'd rather it replace the previous one, but perhaps because the Title bar is different, it simply creates a new entry. This creates a degree of unpredictability for those who don't really care or think about titles, especially since "If you specify the title, it will be matched first," Maybe the title is the functionality that people would miss if multiples didn't accumulate, I'm not sure. 

But for those who don't intentionally have, say, five identical processes with five different Titles all saving to different places, an overwrite option might be nice.

Just an idea, since I didn't already see it. Thanks!

**Comment by caoyue** [comment] 2023-04-17 01:46
Closing as dupe of #55

**Closed by caoyue** 2023-04-17 01:46 UTC
Labels: enhancement
