### ISSUE TITLE
Option to disable creation of second entry with title on save

### ISSUE THREAD

**Issue by apawelec** [caoyue/WindowResizer#52] opened 2023-04-14 06:00 UTC
Personally I never use windows title matching (at least so far) and delete it every time when save new window config (or edit existing one). It would be nice to have an option to not create it - maybe even better with some kind of combo with 3 options "save both, only process for all windows, only process with matching window title", for users that do opposite way ;).

**Comment by caoyue** [comment] 2023-04-17 01:45
Closing as dupe of #55

**Closed** 2023-04-17 01:46 UTC
