### ISSUE TITLE
Chrome windows not auto-positioning

### ISSUE THREAD

**Issue by GaelionL** [caoyue/WindowResizer#51] opened 2023-04-08 12:40 UTC
Hello! Thanks for this very useful tool!
Everything works perfectly for me, except for Chrome windows, which do not automatically get positioned. 
They do when I press the Restore hotkey though, it's only the auto-position that is ignored, and only with Chrome windows.

Maybe this happens because Chrome windows take a while to be titled (until the website loads on that window)? If so, maybe having the option to specify in some cases a small delay before trying to auto-position would help?

Thanks!

**Comment by caoyue** [comment] 2023-04-10 08:41
Have you tried checking auto resize on chrome.exe with title "*"? It will ignore the title for matching.
Just like the picture below, it works fine for me.
![image](https://user-images.githubusercontent.com/522324/230864967-87ff573f-0d83-4e58-8632-555075f1d70e.png)

**Comment by GaelionL** [comment] 2023-04-11 09:02
Thanks for the reply.
I need to differentiate them by name, because I use some websites as Chrome Apps on their own window, so the only way to differentiate them would be by the name?
It is not possible as of now to automatically position/resize different Chrome Apps? Would be very cool to be able to. 
Thanks!

**Comment by caoyue** [comment] 2023-04-11 09:57
> Thanks for the reply. I need to differentiate them by name, because I use some websites as Chrome Apps on their own window, so the only way to differentiate them would be by the name? It is not possible as of now to automatically position/resize different Chrome Apps? Would be very cool to be able to. Thanks!

Oh, I get it.
The program uses the title when the window is created, and if the title is not loaded at that time, it will not be matched.
I will think about this and see if it can be handled by adding a little delay.

**Comment by GaelionL** [comment] 2023-04-11 16:05
That would be great! Thank you very much!

**Comment by caoyue** [comment] 2023-04-17 01:49
Closing as dupe of #56

**Closed by caoyue** 2023-04-17 01:49 UTC

**Comment by GaelionL** [comment] 2023-12-20 00:49
> That would be great! Thank you very much!
The new delay auto resize delay feature totally solved the problem. Thanks very much for implementing it.
Just bought the app on MS store to thank you 🙂
